name: Run Price Scraper Twice Daily

on:
  schedule:
    # 00:00 and 12:00 Netherlands time (Europe/Amsterdam is UTC+1 or +2 with DST)
    - cron: '0 22 * * *'  # 00:00 NL time = 22:00 UTC
    - cron: '0 10 * * *'  # 12:00 NL time = 10:00 UTC
  workflow_dispatch:  # allows manual run from GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and Push Updated CSVs
        run: |
          git config user.name "laxest65"
          git config user.email "laxest65@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/laxest65/price-scraper.git
          git add simple_product_pricescrape.csv child_product_pricescrape.csv
          git commit -m "Update scraped prices - $(date -u +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push || echo "Nothing to push"

      - name: Test send email with Python script
        run: python send_test_email.py
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
