name: Test Git Push with PAT

on:
  workflow_dispatch:

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set Git identity
        run: |
          git config user.name "laxest65"
          git config user.email "laxest65@users.noreply.github.com"

      - name: Make a test change
        run: |
          echo "Test at $(date)" >> test_output.txt
          git add test_output.txt
          git commit -m "Test push - $(date)"
          
      - name: Push to GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/laxest65/price-scraper.git
          git push origin main
